name: Deploy Frontend to Prod

on:
  push:
    branches:
      - main  # Cambiamos a la rama principal

# VARIABLES GLOBALES PARA PRODUCCIÓN
env:
  VITE_API_CHAT: "https://api-v30.pida-ai.com"
  VITE_FIREBASE_API_KEY: "AIzaSyB6Prs45DGOTHWXByHjpLexntvZDYvVOro"
  VITE_FIREBASE_AUTH_DOMAIN: "pida-ai-prod.firebaseapp.com"
  VITE_FIREBASE_PROJECT_ID: "pida-ai-prod"
  VITE_FIREBASE_STORAGE_BUCKET: "pida-ai-prod.firebasestorage.app"
  VITE_FIREBASE_MESSAGING_SENDER_ID: "987232357291"
  VITE_FIREBASE_APP_ID: "1:987232357291:web:b5dd4580f4afb40e11e0ee"
  VITE_FIREBASE_MEASUREMENT_ID: "G-15KNMREGVL"

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # CONSTRUCCIÓN APP PRINCIPAL
      - name: Instalar dependencias (Principal)
        working-directory: ./portal-principal
        run: npm install

      - name: Construir proyecto (Principal)
        working-directory: ./portal-principal
        run: npm run build

      # CONSTRUCCIÓN APP ADMIN
      - name: Instalar dependencias (Admin)
        working-directory: ./portal-admin
        run: npm install

      - name: Construir proyecto (Admin)
        working-directory: ./portal-admin
        run: npm run build

      # DESPLIEGUE SEGURO (WIF)
      - name: Autenticación Segura en Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/736009271165/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
          service_account: 'sa-github-deployer@pida-ai-prod.iam.gserviceaccount.com' # Cuenta de PROD

      - name: Instalar Firebase CLI
        run: npm install -g firebase-tools

      - name: Desplegar ambos sitios en Firebase Hosting
        run: firebase deploy --only hosting --project pida-ai-prod --non-interactive --debug